### ISSUE TITLE
JSBN required for build

### ISSUE THREAD

**Issue by TACIXAT** [alax/jsrp#8]
```
$ browserify jsrp.js --standalone jsrp > jsrp-browser.js
Error: Cannot find module 'jsbn' from '/path/to/jsrp/lib'
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:117:15)
$ npm install jsbn
$ browserify jsrp.js --standalone jsrp > jsrp-browser.js
```

**Comment by alax** [comment]
Make sure that you run `npm install` first, as you would with any package you're trying to build.
